## Naive Baye's Machine Learning Algorithms Implementation

In [1]:
from sklearn.datasets import load_iris

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
X,y = load_iris(return_X_y=True)

In [4]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [7]:
X_train

array([[5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 2.2, 5. , 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2.9, 3.6, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [6.1, 3. , 4.6, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [5.3, 3.7, 1.5, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [6.4, 2.7, 5.3, 1.9],
       [5.7, 3. , 4.2, 1.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.9, 3.1, 4.9, 1.5],
       [4.6, 3.1, 1.5, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5.1, 2.5, 3. , 1.1],
       [4.6, 3.4, 1.4, 0.3],
       [6.2, 2

In [8]:
from sklearn.naive_bayes import GaussianNB

In [9]:
gnb = GaussianNB()

In [10]:
gnb.fit(X_train,y_train)

GaussianNB()

In [11]:
y_pred = gnb.predict(X_test)

In [12]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0])

In [13]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [14]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [15]:
import seaborn as sns

In [16]:

data = sns.load_dataset('tips')

In [17]:
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [19]:
data['time'].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [20]:
data['smoker'].unique()

['No', 'Yes']
Categories (2, object): ['Yes', 'No']

In [21]:
import pandas as pd

In [22]:
encoder_data

NameError: name 'encoder_data' is not defined

In [ ]:
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
data.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()


In [ ]:
data['total_bill']=scaler.fit_transform(data[["total_bill"]])

In [ ]:
data['tip']=scaler.fit_transform(data[["tip"]])

In [ ]:
data.head()

total_bill       tip     sex smoker  day    time  size
0   -0.314711 -1.439947  Female     No  Sun  Dinner     2
1   -1.063235 -0.969205    Male     No  Sun  Dinner     3
2    0.137780  0.363356    Male     No  Sun  Dinner     3
3    0.438315  0.225754    Male     No  Sun  Dinner     2
4    0.540745  0.443020  Female     No  Sun  Dinner     4

In [ ]:
import numpy as np

In [ ]:
## Encoding
data['sex']=np.where(data['sex'].str.contains("Female"),0,1)
data['smoker']=np.where(data['smoker'].str.contains("No"),0,1)
# data['time']=np.where(data['time'].str.contains("Dinner"),0,1)


In [ ]:
data.head()

total_bill       tip  sex  smoker  day    time  size
0   -0.314711 -1.439947    0       0  Sun  Dinner     2
1   -1.063235 -0.969205    1       0  Sun  Dinner     3
2    0.137780  0.363356    1       0  Sun  Dinner     3
3    0.438315  0.225754    1       0  Sun  Dinner     2
4    0.540745  0.443020    0       0  Sun  Dinner     4

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoded=encoder.fit_transform(data[['day']]).toarray()
encoder_data = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

In [ ]:
encoder_data

day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [ ]:
data = pd.concat([data, encoder_data], ignore_index=True)


In [ ]:
data.head()

total_bill       tip  sex  smoker  day    time  size  day_Fri  day_Sat  \
0   -0.314711 -1.439947  0.0     0.0  Sun  Dinner   2.0      NaN      NaN   
1   -1.063235 -0.969205  1.0     0.0  Sun  Dinner   3.0      NaN      NaN   
2    0.137780  0.363356  1.0     0.0  Sun  Dinner   3.0      NaN      NaN   
3    0.438315  0.225754  1.0     0.0  Sun  Dinner   2.0      NaN      NaN   
4    0.540745  0.443020  0.0     0.0  Sun  Dinner   4.0      NaN      NaN   

   day_Sun  day_Thur  
0      NaN       NaN  
1      NaN       NaN  
2      NaN       NaN  
3      NaN       NaN  
4      NaN       NaN

In [ ]:
data[["day_Fri"	,"day_Sat",	"day_Sun",	"day_Thur"]].fillna(0)

day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      0.0       0.0
1        0.0      0.0      0.0       0.0
2        0.0      0.0      0.0       0.0
3        0.0      0.0      0.0       0.0
4        0.0      0.0      0.0       0.0
..       ...      ...      ...       ...
483      0.0      1.0      0.0       0.0
484      0.0      1.0      0.0       0.0
485      0.0      1.0      0.0       0.0
486      0.0      1.0      0.0       0.0
487      0.0      0.0      0.0       1.0

[488 rows x 4 columns]

In [ ]:
data.tail()

total_bill  tip  sex  smoker  day time  size  day_Fri  day_Sat  day_Sun  \
483         NaN  NaN  NaN     NaN  NaN  NaN   NaN      0.0      1.0      0.0   
484         NaN  NaN  NaN     NaN  NaN  NaN   NaN      0.0      1.0      0.0   
485         NaN  NaN  NaN     NaN  NaN  NaN   NaN      0.0      1.0      0.0   
486         NaN  NaN  NaN     NaN  NaN  NaN   NaN      0.0      1.0      0.0   
487         NaN  NaN  NaN     NaN  NaN  NaN   NaN      0.0      0.0      0.0   

     day_Thur  
483       0.0  
484       0.0  
485       0.0  
486       0.0  
487       1.0

In [ ]:
X = data[["total_bill"	,"tip"	,"sex"	,"smoker"	,"day",	"size"	,"day_Fri"	,"day_Sat",	"day_Sun",	"day_Thur"]]
y = data[['time']]

In [ ]:
X

total_bill       tip  sex  smoker  day  size  day_Fri  day_Sat  day_Sun  \
0     -0.314711 -1.439947  0.0     0.0  Sun   2.0      NaN      NaN      NaN   
1     -1.063235 -0.969205  1.0     0.0  Sun   3.0      NaN      NaN      NaN   
2      0.137780  0.363356  1.0     0.0  Sun   3.0      NaN      NaN      NaN   
3      0.438315  0.225754  1.0     0.0  Sun   2.0      NaN      NaN      NaN   
4      0.540745  0.443020  0.0     0.0  Sun   4.0      NaN      NaN      NaN   
..          ...       ...  ...     ...  ...   ...      ...      ...      ...   
483         NaN       NaN  NaN     NaN  NaN   NaN      0.0      1.0      0.0   
484         NaN       NaN  NaN     NaN  NaN   NaN      0.0      1.0      0.0   
485         NaN       NaN  NaN     NaN  NaN   NaN      0.0      1.0      0.0   
486         NaN       NaN  NaN     NaN  NaN   NaN      0.0      1.0      0.0   
487         NaN       NaN  NaN     NaN  NaN   NaN      0.0      0.0      0.0   

     day_Thur  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN  
..        ...  
483       0.0  
484       0.0  
485       0.0  
486       0.0  
487       1.0  

[488 rows x 10 columns]