## Adaboost,Gradient Boost ,XGboost Implementation

## Classification

In [5]:
import numpy as np
import pandas as pd

In [1]:
# !pip install Xgboost

  Obtaining dependency information for Xgboost from https://files.pythonhosted.org/packages/bc/43/242432efc3f60052a4a534dc4926b21e236ab4ec8d4920c593da3f65c65d/xgboost-2.0.2-py3-none-win_amd64.whl.metadata
   ---------------------------------------- 0.0/99.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/99.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/99.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/99.8 MB 217.9 kB/s eta 0:07:38
   ---------------------------------------- 0.0/99.8 MB 217.9 kB/s eta 0:07:38
   ---------------------------------------- 0.0/99.8 MB 217.9 kB/s eta 0:07:38
   ---------------------------------------- 0.0/99.8 MB 217.9 kB/s eta 0:07:38
   ---------------------------------------- 0.0/99.8 MB 217.9 kB/s eta 0:07:38
   ---------------------------------------- 0.0/99.8 MB 217.9 kB/s eta 0:07:38
   ---------------------------------------- 0.1/99.8 MB 340.5 kB/s eta 0:04:53
   -----------------------------

In [7]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples=1000, n_features=4, n_informative=2, n_redundant=0,random_state=0, shuffle=False)

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [9]:
X_train

array([[ 0.96255595, -1.40026863, -1.87731282,  1.08833521],
       [-0.55429445,  0.85559441,  0.0890762 , -0.12915348],
       [ 1.17276481, -1.06678623,  0.02816987,  1.9783727 ],
       ...,
       [ 0.79397293,  0.02908038, -1.0651481 , -2.16366101],
       [-1.31873331,  1.90648232,  1.32570796, -0.34198228],
       [ 0.15567143, -1.17581558, -0.44791484, -0.19871506]])

In [10]:
X_test

array([[ 1.37105506, -0.94050371, -0.48948242,  0.76354147],
       [ 0.82794414, -1.11989774, -0.73381673, -0.53243766],
       [ 0.36633802, -1.66146275, -0.2677478 ,  0.21317626],
       ...,
       [-1.3184946 ,  0.38965026,  0.10233585, -0.22409237],
       [ 0.44880983, -1.8173685 ,  0.97513841, -1.32933657],
       [-1.17440571, -1.08996336, -1.09389506,  0.2057968 ]])

In [11]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xb

In [12]:
classifier1 = AdaBoostClassifier()
classifier1.fit(X_train,y_train)

AdaBoostClassifier()

In [13]:
y_pred1 = classifier1.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [15]:
print(confusion_matrix(y_test,y_pred1))
print(accuracy_score(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

[[153  13]
 [ 12 152]]
0.9242424242424242
              precision    recall  f1-score   support

           0       0.93      0.92      0.92       166
           1       0.92      0.93      0.92       164

    accuracy                           0.92       330
   macro avg       0.92      0.92      0.92       330
weighted avg       0.92      0.92      0.92       330



In [16]:
classifier2 = GradientBoostingClassifier()
classifier2.fit(X_train,y_train)

GradientBoostingClassifier()

In [17]:
y_pred2 = classifier2.predict(X_test)

In [18]:
print(confusion_matrix(y_test,y_pred2))
print(accuracy_score(y_test,y_pred2))
print(classification_report(y_test,y_pred2))

[[153  13]
 [  7 157]]
0.9393939393939394
              precision    recall  f1-score   support

           0       0.96      0.92      0.94       166
           1       0.92      0.96      0.94       164

    accuracy                           0.94       330
   macro avg       0.94      0.94      0.94       330
weighted avg       0.94      0.94      0.94       330



In [19]:
classifier3 = xb.XGBClassifier()
classifier3.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [22]:
y_pred3 = classifier3.predict(X_test)

In [23]:
print(confusion_matrix(y_test,y_pred3))
print(accuracy_score(y_test,y_pred3))
print(classification_report(y_test,y_pred3))

[[155  11]
 [  9 155]]
0.9393939393939394
              precision    recall  f1-score   support

           0       0.95      0.93      0.94       166
           1       0.93      0.95      0.94       164

    accuracy                           0.94       330
   macro avg       0.94      0.94      0.94       330
weighted avg       0.94      0.94      0.94       330



## Regression Task

In [24]:
from sklearn.datasets import make_regression
X, y = make_regression(n_features=4, n_informative=2,
                       random_state=0, shuffle=False)

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [26]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
import xgboost as xb

In [44]:
regressor1 = AdaBoostRegressor()


In [45]:
regressor1.fit(X_train,y_train)

AdaBoostRegressor()

In [46]:
y_pred1 = regressor1.predict(X_test)

In [47]:
from sklearn.metrics import r2_score

In [48]:
r2_score1 = r2_score(y_test,y_pred1)

In [49]:
print(r2_score1)

0.924848413230164


In [50]:
regressor2 = GradientBoostingRegressor()

In [51]:
regressor2.fit(X_train,y_train)

GradientBoostingRegressor()

In [52]:
y_pred2 = regressor2.predict(X_test)

In [53]:
r2_score2 = r2_score(y_test,y_pred2)

In [54]:
print(r2_score2)

0.9385130347010899


In [55]:
regressor3 = xb.XGBRegressor()

In [56]:
regressor3.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [57]:
y_pred3 = regressor3.predict(X_test)

In [58]:
r2_score3 = r2_score(y_test,y_pred3)

In [60]:
print(r2_score3)

0.9109910707496999
