In [1]:
import numpy as np


#numpy - Array Manipulation

In [2]:
arr = np.random.randint(1,10,(4,4))

In [3]:
arr

array([[8, 4, 7, 2],
       [2, 4, 6, 7],
       [8, 1, 2, 3],
       [3, 6, 2, 5]])

In [4]:
arr.reshape(8,2)

array([[8, 4],
       [7, 2],
       [2, 4],
       [6, 7],
       [8, 1],
       [2, 3],
       [3, 6],
       [2, 5]])

In [5]:
arr

array([[8, 4, 7, 2],
       [2, 4, 6, 7],
       [8, 1, 2, 3],
       [3, 6, 2, 5]])

In [6]:
arr.T

array([[8, 2, 8, 3],
       [4, 4, 1, 6],
       [7, 6, 2, 2],
       [2, 7, 3, 5]])

In [7]:
arr.flatten()  # it is used to make one dimetional array 

array([8, 4, 7, 2, 2, 4, 6, 7, 8, 1, 2, 3, 3, 6, 2, 5])

In [8]:
np.expand_dims(arr, axis=1)

array([[[8, 4, 7, 2]],

       [[2, 4, 6, 7]],

       [[8, 1, 2, 3]],

       [[3, 6, 2, 5]]])

In [9]:
np.expand_dims(arr,axis=0)  #covert 2 dim to 3 dim

array([[[8, 4, 7, 2],
        [2, 4, 6, 7],
        [8, 1, 2, 3],
        [3, 6, 2, 5]]])

In [10]:
data = np.array([[1],[2],[3]])

In [11]:
np.squeeze(data ) # it is used to squeese the 

array([1, 2, 3])

In [12]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [13]:
np.roll(data, 2) # roetete the element'/

array([[2],
       [3],
       [1]])

In [14]:
np.diag(np.array([1,2,3,4])) # diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#binary operation

In [15]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))


In [16]:
arr1

array([[9, 5, 6, 2],
       [6, 1, 9, 9],
       [6, 7, 3, 8]])

In [17]:
arr2

array([[1, 7, 6, 1],
       [8, 7, 6, 8],
       [9, 5, 3, 1]])

In [18]:
arr1+arr2

array([[10, 12, 12,  3],
       [14,  8, 15, 17],
       [15, 12,  6,  9]])

In [19]:
arr1/arr2

array([[9.        , 0.71428571, 1.        , 2.        ],
       [0.75      , 0.14285714, 1.5       , 1.125     ],
       [0.66666667, 1.4       , 1.        , 8.        ]])

In [20]:
arr1**arr2

array([[       9,    78125,    46656,        2],
       [ 1679616,        1,   531441, 43046721],
       [10077696,    16807,       27,        8]])

In [21]:
-arr1

array([[-9, -5, -6, -2],
       [-6, -1, -9, -9],
       [-6, -7, -3, -8]])

In [22]:
arr1

array([[9, 5, 6, 2],
       [6, 1, 9, 9],
       [6, 7, 3, 8]])

In [23]:
arr1 > arr2

array([[ True, False, False,  True],
       [False, False,  True,  True],
       [False,  True, False,  True]])

#numpy - String Funcation

In [24]:
arr = np.array(["Adhi","gowda"])

In [25]:
np.char.upper(arr)

array(['ADHI', 'GOWDA'], dtype='<U5')

In [26]:
np.char.capitalize(arr)

array(['Adhi', 'Gowda'], dtype='<U5')

In [27]:
np.char.title(arr)


array(['Adhi', 'Gowda'], dtype='<U5')

#Numpy - Mathamatical funcation

In [28]:
arr1

array([[9, 5, 6, 2],
       [6, 1, 9, 9],
       [6, 7, 3, 8]])

In [29]:
np.sin(arr1)

array([[ 0.41211849, -0.95892427, -0.2794155 ,  0.90929743],
       [-0.2794155 ,  0.84147098,  0.41211849,  0.41211849],
       [-0.2794155 ,  0.6569866 ,  0.14112001,  0.98935825]])

In [30]:
np.cos(arr1)

array([[-0.91113026,  0.28366219,  0.96017029, -0.41614684],
       [ 0.96017029,  0.54030231, -0.91113026, -0.91113026],
       [ 0.96017029,  0.75390225, -0.9899925 , -0.14550003]])

In [31]:
np.tan(arr1)

array([[-0.45231566, -3.38051501, -0.29100619, -2.18503986],
       [-0.29100619,  1.55740772, -0.45231566, -0.45231566],
       [-0.29100619,  0.87144798, -0.14254654, -6.79971146]])

In [32]:
np.log(arr1)

array([[2.19722458, 1.60943791, 1.79175947, 0.69314718],
       [1.79175947, 0.        , 2.19722458, 2.19722458],
       [1.79175947, 1.94591015, 1.09861229, 2.07944154]])

In [33]:
np.power(arr1,2)

array([[81, 25, 36,  4],
       [36,  1, 81, 81],
       [36, 49,  9, 64]], dtype=int32)

In [34]:
np.mean(arr1)

5.916666666666667

In [35]:
np.median(arr1)


6.0

In [36]:
np.std(arr1)


2.628635049264584

In [37]:
np.var(arr1)

6.909722222222221

#numpy - Arithmetic operation

In [38]:
arr1 

array([[9, 5, 6, 2],
       [6, 1, 9, 9],
       [6, 7, 3, 8]])

In [39]:
arr2

array([[1, 7, 6, 1],
       [8, 7, 6, 8],
       [9, 5, 3, 1]])

In [40]:
arr1-arr2

array([[ 8, -2,  0,  1],
       [-2, -6,  3,  1],
       [-3,  2,  0,  7]])

In [41]:
np.subtract(arr1,arr2)

array([[ 8, -2,  0,  1],
       [-2, -6,  3,  1],
       [-3,  2,  0,  7]])

In [42]:
np.multiply(arr1,arr2)

array([[ 9, 35, 36,  2],
       [48,  7, 54, 72],
       [54, 35,  9,  8]])

In [43]:
np.mod(arr1,arr2) #reminder

array([[0, 5, 0, 0],
       [6, 1, 3, 1],
       [6, 2, 0, 0]])

In [44]:
np.power(arr1,arr2)

array([[       9,    78125,    46656,        2],
       [ 1679616,        1,   531441, 43046721],
       [10077696,    16807,       27,        8]])

In [45]:
np.sqrt(arr1)

array([[3.        , 2.23606798, 2.44948974, 1.41421356],
       [2.44948974, 1.        , 3.        , 3.        ],
       [2.44948974, 2.64575131, 1.73205081, 2.82842712]])

#numpy - Statistical fuuncation

In [46]:
np.mean(arr1)

5.916666666666667

In [47]:
np.std(arr1)

2.628635049264584

In [48]:
np.median(arr1)

6.0