sort , search, & counting funcation

In [7]:
import numpy as np

In [8]:
arr = np.array([8,6,43,4,62,45])

In [9]:
arr

array([ 8,  6, 43,  4, 62, 45])

In [10]:
np.sort(arr)

array([ 4,  6,  8, 43, 45, 62])

In [11]:
np.sort(arr, axis=0)

array([ 4,  6,  8, 43, 45, 62])

In [12]:
np.sort(arr, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
np.searchsorted(arr,6)

4

In [ ]:
arr

array([ 8,  6, 43,  4, 62, 45])

In [ ]:
arr = np.array([8,0,6,0,2,43,4,62,45])

In [ ]:
arr

array([ 8,  0,  6,  0,  2, 43,  4, 62, 45])

In [ ]:
np.count_nonzero(arr)

7

In [ ]:
np.where(arr > 0)

(array([0, 2, 4, 5, 6, 7, 8], dtype=int64),)

In [ ]:
np.extract(arr > 2,arr)

array([ 8,  6, 43,  4, 62, 45])

Numpy - byte swapping

In [ ]:
arr.byteswap()

array([ 134217728,          0,  100663296,          0,   33554432,
        721420288,   67108864, 1040187392,  754974720])

In [ ]:
arr

array([ 8,  0,  6,  0,  2, 43,  4, 62, 45])

In [ ]:
arr.byteswap(True)

array([ 134217728,          0,  100663296,          0,   33554432,
        721420288,   67108864, 1040187392,  754974720])

In [ ]:
arr

array([ 134217728,          0,  100663296,          0,   33554432,
        721420288,   67108864, 1040187392,  754974720])

Numpy copies and views

In [ ]:
arr

array([ 134217728,          0,  100663296,          0,   33554432,
        721420288,   67108864, 1040187392,  754974720])

In [ ]:
a = np.copy(arr)  # deepcopy

In [ ]:
b = arr.view() # solo copy

In [ ]:
b

array([ 8,  0,  6,  0,  2, 43,  4, 62, 45])

In [ ]:
b[0] = 456

In [ ]:
b

array([456,   0,   6,   0,   2,  43,   4,  62,  45])

In [ ]:
arr

array([456,   0,   6,   0,   2,  43,   4,  62,  45])

Numpy - matrix library

In [ ]:
import numpy.matlib as nm

In [ ]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

numpy - liner algebra

In [ ]:
arr

array([456,   0,   6,   0,   2,  43,   4,  62,  45])

In [ ]:
arr1 = np.random.randint([[2,3],[4,5]])

In [ ]:
arr2 = np.random.randint([[5,3],[2,5]])

In [ ]:
arr

array([456,   0,   6,   0,   2,  43,   4,  62,  45])

In [ ]:
arr1

array([[0, 1],
       [1, 0]])

In [ ]:
arr2

array([[4, 1],
       [1, 2]])

In [ ]:
np.dot(arr1,arr2)

array([[1, 2],
       [4, 1]])

In [ ]:
arr1@arr2

array([[1, 2],
       [4, 1]])