In [1]:
import numpy as np


#numpy - Array Manipulation

In [4]:
arr = np.random.randint(1,10,(4,4))

In [5]:
arr

array([[2, 1, 4, 7],
       [9, 2, 2, 6],
       [7, 7, 8, 1],
       [7, 5, 5, 5]])

In [6]:
arr.reshape(8,2)

array([[2, 1],
       [4, 7],
       [9, 2],
       [2, 6],
       [7, 7],
       [8, 1],
       [7, 5],
       [5, 5]])

In [7]:
arr

array([[2, 1, 4, 7],
       [9, 2, 2, 6],
       [7, 7, 8, 1],
       [7, 5, 5, 5]])

In [8]:
arr.T

array([[2, 9, 7, 7],
       [1, 2, 7, 5],
       [4, 2, 8, 5],
       [7, 6, 1, 5]])

In [9]:
arr.flatten()  # it is used to make one dimetional array 

array([2, 1, 4, 7, 9, 2, 2, 6, 7, 7, 8, 1, 7, 5, 5, 5])

In [13]:
np.expand_dims(arr, axis=1)

array([[[2, 1, 4, 7]],

       [[9, 2, 2, 6]],

       [[7, 7, 8, 1]],

       [[7, 5, 5, 5]]])

In [14]:
np.expand_dims(arr,axis=0)  #covert 2 dim to 3 dim

array([[[2, 1, 4, 7],
        [9, 2, 2, 6],
        [7, 7, 8, 1],
        [7, 5, 5, 5]]])

In [16]:
data = np.array([[1],[2],[3]])

In [17]:
np.squeeze(data ) # it is used to squeese the 

array([1, 2, 3])

In [18]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [20]:
np.roll(data, 2) # roetete the element'/

array([[2],
       [3],
       [1]])

In [22]:
np.diag(np.array([1,2,3,4])) # diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#binary operation

In [23]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))


In [24]:
arr1

array([[3, 4, 7, 3],
       [1, 9, 2, 2],
       [8, 9, 3, 7]])

In [25]:
arr2

array([[7, 7, 4, 2],
       [9, 6, 4, 5],
       [1, 3, 4, 9]])

In [26]:
arr1+arr2

array([[10, 11, 11,  5],
       [10, 15,  6,  7],
       [ 9, 12,  7, 16]])

In [27]:
arr1/arr2

array([[0.42857143, 0.57142857, 1.75      , 1.5       ],
       [0.11111111, 1.5       , 0.5       , 0.4       ],
       [8.        , 3.        , 0.75      , 0.77777778]])

In [28]:
arr1**arr2

array([[    2187,    16384,     2401,        9],
       [       1,   531441,       16,       32],
       [       8,      729,       81, 40353607]])

In [29]:
-arr1

array([[-3, -4, -7, -3],
       [-1, -9, -2, -2],
       [-8, -9, -3, -7]])

In [30]:
arr1

array([[3, 4, 7, 3],
       [1, 9, 2, 2],
       [8, 9, 3, 7]])

In [31]:
arr1 > arr2

array([[False, False,  True,  True],
       [False,  True, False, False],
       [ True,  True, False, False]])

#numpy - String Funcation

In [32]:
arr = np.array(["Adhi","gowda"])

In [33]:
np.char.upper(arr)

array(['ADHI', 'GOWDA'], dtype='<U5')

In [34]:
np.char.capitalize(arr)

array(['Adhi', 'Gowda'], dtype='<U5')

In [35]:
np.char.title(arr)


array(['Adhi', 'Gowda'], dtype='<U5')

#Numpy - Mathamatical funcation

In [36]:
arr1

array([[3, 4, 7, 3],
       [1, 9, 2, 2],
       [8, 9, 3, 7]])

In [38]:
np.sin(arr1)

array([[ 0.14112001, -0.7568025 ,  0.6569866 ,  0.14112001],
       [ 0.84147098,  0.41211849,  0.90929743,  0.90929743],
       [ 0.98935825,  0.41211849,  0.14112001,  0.6569866 ]])

In [39]:
np.cos(arr1)

array([[-0.9899925 , -0.65364362,  0.75390225, -0.9899925 ],
       [ 0.54030231, -0.91113026, -0.41614684, -0.41614684],
       [-0.14550003, -0.91113026, -0.9899925 ,  0.75390225]])

In [40]:
np.tan(arr1)

array([[-0.14254654,  1.15782128,  0.87144798, -0.14254654],
       [ 1.55740772, -0.45231566, -2.18503986, -2.18503986],
       [-6.79971146, -0.45231566, -0.14254654,  0.87144798]])

In [41]:
np.log(arr1)

array([[1.09861229, 1.38629436, 1.94591015, 1.09861229],
       [0.        , 2.19722458, 0.69314718, 0.69314718],
       [2.07944154, 2.19722458, 1.09861229, 1.94591015]])

In [43]:
np.power(arr1,2)

array([[ 9, 16, 49,  9],
       [ 1, 81,  4,  4],
       [64, 81,  9, 49]], dtype=int32)

In [44]:
np.mean(arr1)

4.833333333333333

In [45]:
np.median(arr1)


3.5

In [47]:
np.std(arr1)


2.823512391016236

In [48]:
np.var(arr1)

7.972222222222222

#numpy - Arithmetic operation

In [50]:
arr1 

array([[3, 4, 7, 3],
       [1, 9, 2, 2],
       [8, 9, 3, 7]])

In [51]:
arr2

array([[7, 7, 4, 2],
       [9, 6, 4, 5],
       [1, 3, 4, 9]])

In [52]:
arr1-arr2

array([[-4, -3,  3,  1],
       [-8,  3, -2, -3],
       [ 7,  6, -1, -2]])

In [53]:
np.subtract(arr1,arr2)

array([[-4, -3,  3,  1],
       [-8,  3, -2, -3],
       [ 7,  6, -1, -2]])

In [54]:
np.multiply(arr1,arr2)

array([[21, 28, 28,  6],
       [ 9, 54,  8, 10],
       [ 8, 27, 12, 63]])

In [56]:
np.mod(arr1,arr2) #reminder

array([[3, 4, 3, 1],
       [1, 3, 2, 2],
       [0, 0, 3, 7]])

In [57]:
np.power(arr1,arr2)

array([[    2187,    16384,     2401,        9],
       [       1,   531441,       16,       32],
       [       8,      729,       81, 40353607]])

In [59]:
np.sqrt(arr1)

array([[1.73205081, 2.        , 2.64575131, 1.73205081],
       [1.        , 3.        , 1.41421356, 1.41421356],
       [2.82842712, 3.        , 1.73205081, 2.64575131]])

#numpy - Statistical fuuncation

In [60]:
np.mean(arr1)

4.833333333333333

In [61]:
np.std(arr1)

2.823512391016236

In [62]:
np.median(arr1)

3.5