In [1]:
import numpy as np

In [2]:
range(0,5)

range(0, 5)

In [3]:
list(range(0,4))

[0, 1, 2, 3]

In [4]:
list(range(0.5, 10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(0,4)

array([0, 1, 2, 3])

In [ ]:
np.arange(0.5, 10.5)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [ ]:
np.arange(0.5, 10.5,2)


array([0.5, 2.5, 4.5, 6.5, 8.5])

In [ ]:
list(np.arange(0.5, 10.5,2))

[0.5, 2.5, 4.5, 6.5, 8.5]

In [ ]:
np.linspace(2, 6, 20)  # used to print the value between the range and split the values based on the given value

array([2.        , 2.21052632, 2.42105263, 2.63157895, 2.84210526,
       3.05263158, 3.26315789, 3.47368421, 3.68421053, 3.89473684,
       4.10526316, 4.31578947, 4.52631579, 4.73684211, 4.94736842,
       5.15789474, 5.36842105, 5.57894737, 5.78947368, 6.        ])

In [ ]:
np.logspace(1,5)

array([1.00000000e+01, 1.20679264e+01, 1.45634848e+01, 1.75751062e+01,
       2.12095089e+01, 2.55954792e+01, 3.08884360e+01, 3.72759372e+01,
       4.49843267e+01, 5.42867544e+01, 6.55128557e+01, 7.90604321e+01,
       9.54095476e+01, 1.15139540e+02, 1.38949549e+02, 1.67683294e+02,
       2.02358965e+02, 2.44205309e+02, 2.94705170e+02, 3.55648031e+02,
       4.29193426e+02, 5.17947468e+02, 6.25055193e+02, 7.54312006e+02,
       9.10298178e+02, 1.09854114e+03, 1.32571137e+03, 1.59985872e+03,
       1.93069773e+03, 2.32995181e+03, 2.81176870e+03, 3.39322177e+03,
       4.09491506e+03, 4.94171336e+03, 5.96362332e+03, 7.19685673e+03,
       8.68511374e+03, 1.04811313e+04, 1.26485522e+04, 1.52641797e+04,
       1.84206997e+04, 2.22299648e+04, 2.68269580e+04, 3.23745754e+04,
       3.90693994e+04, 4.71486636e+04, 5.68986603e+04, 6.86648845e+04,
       8.28642773e+04, 1.00000000e+05])

In [ ]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3,4,2,3)) # 2*3 like 4 matrics and 3 set of matrics

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones((3,4))

In [ ]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
arr*2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [ ]:
np.empty((3,4))

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr1 = np.eye(5)

In [ ]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [ ]:
np.random.rand(2,3) # here mean can be anything std 

array([[0.15937858, 0.95862622, 0.18140017],
       [0.8712528 , 0.23426194, 0.64488679]])

In [ ]:
np.random.randn(2,3) # standard normal distribution  # mean = 0 and std = 1

array([[ 0.92682268,  0.03587405, -1.32291684],
       [-0.49964419,  0.32615846,  0.55359072]])

In [ ]:
np.random.randint(3,5, (3,4))

array([[4, 4, 4, 3],
       [4, 3, 3, 4],
       [3, 4, 3, 4]])

In [ ]:
arr2 = np.random.randint(3,5, (3,4))

In [ ]:
arr2

array([[4, 3, 3, 3],
       [4, 4, 3, 4],
       [4, 4, 4, 3]])

In [ ]:
arr2.size

12

In [ ]:
arr2.reshape(6,2) # data not changed but re shaped

array([[4, 3],
       [3, 3],
       [4, 4],
       [3, 4],
       [4, 4],
       [4, 3]])

In [ ]:
arr2.reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [ ]:
arr2.reshape(4,1)

ValueError: cannot reshape array of size 12 into shape (4,1)

In [ ]:
arr2.reshape(4,14322524)

ValueError: cannot reshape array of size 12 into shape (4,14322524)

In [ ]:
arr2.reshape(2,2,3)

array([[[4, 3, 3],
        [3, 4, 4]],

       [[3, 4, 4],
        [4, 4, 3]]])

In [ ]:
arr2.reshape(2,2,3)

array([[[4, 3, 3],
        [3, 4, 4]],

       [[3, 4, 4],
        [4, 4, 3]]])

In [ ]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[4]]],


         [[[3]]],


         [[[3]]]],



        [[[[3]]],


         [[[4]]],


         [[[4]]]]],




       [[[[[3]]],


         [[[4]]],


         [[[4]]]],



        [[[[4]]],


         [[[4]]],


         [[[3]]]]]])

In [ ]:
arr1 = np.random.randint(1,10,(5,5))

In [ ]:
arr1

array([[7, 6, 1, 4, 5],
       [7, 4, 9, 6, 9],
       [3, 7, 6, 7, 3],
       [3, 1, 5, 5, 8],
       [6, 8, 2, 7, 9]])

In [ ]:
arr1>8

array([[False, False, False, False, False],
       [False, False,  True, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True]])

In [ ]:
arr1[arr1 > 8]

array([9, 9, 9])

In [ ]:
arr1

array([[7, 6, 1, 4, 5],
       [7, 4, 9, 6, 9],
       [3, 7, 6, 7, 3],
       [3, 1, 5, 5, 8],
       [6, 8, 2, 7, 9]])

In [ ]:
arr1[0,[0,1]]

array([7, 6])

In [ ]:
arr1[2:4,[2,3]]

array([[6, 7],
       [5, 5]])

In [ ]:
arr1 = np.random.randint(1,3,(3,3) )
arr2 = np.random.randint(1,3,(3,3) )


In [ ]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [1, 1, 1]])

In [ ]:
arr2

array([[1, 1, 1],
       [1, 1, 2],
       [1, 1, 2]])

In [ ]:
arr1+arr2

array([[2, 3, 2],
       [2, 3, 3],
       [2, 2, 3]])

In [ ]:
arr1-arr2

array([[ 0,  1,  0],
       [ 0,  1, -1],
       [ 0,  0, -1]])

In [ ]:
arr1*arr2  # it is an index multiplication , THis is not a matrix multiplication

array([[1, 2, 1],
       [1, 2, 2],
       [1, 1, 2]])

In [ ]:
arr1@arr2  # matrix multiplication 

array([[4, 4, 7],
       [4, 4, 7],
       [3, 3, 5]])

In [ ]:
arr1/arr2  

array([[1. , 2. , 1. ],
       [1. , 2. , 0.5],
       [1. , 1. , 0.5]])

In [ ]:
arr1/0

C:\Users\Dell\AppData\Local\Temp\ipykernel_5340\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

#numpy - Breadcasting

In [ ]:
arr = np.zeros((3,4))

In [ ]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
b = np.array([[3,4,5]])

In [ ]:
arr+b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [ ]:
b.T

array([[3],
       [4],
       [5]])

In [ ]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [1, 1, 1]])

In [ ]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.        ],
       [1.        , 1.        , 1.        ]])

In [ ]:
np.log(arr1)

array([[0.        , 0.69314718, 0.        ],
       [0.        , 0.69314718, 0.        ],
       [0.        , 0.        , 0.        ]])

In [ ]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [ ]:
np.mean(arr1)

1.2222222222222223

In [ ]:
np.min(arr1)

1

In [ ]:
np.max(arr1)

2